//
//  CountryCodes.swift
//  MissMatch
//
//  Created by Anatoliy Petrov on 4.8.24..
//

import Foundation

struct Country: Hashable {
    let flag: String
    let code: String
    let name: String
}

class CountryCodes {
        let countryCodes: [Country] = [
            Country(flag: "🇦🇫", code: "+93", name: "Afghanistan"),
            Country(flag: "🇦🇱", code: "+355", name: "Albania"),
            Country(flag: "🇩🇿", code: "+213", name: "Algeria"),
            Country(flag: "🇦🇸", code: "+1-684", name: "American Samoa"),
            Country(flag: "🇦🇩", code: "+376", name: "Andorra"),
            Country(flag: "🇦🇴", code: "+244", name: "Angola"),
            Country(flag: "🇦🇮", code: "+1-264", name: "Anguilla"),
            Country(flag: "🇦🇶", code: "+672", name: "Antarctica"),
            Country(flag: "🇦🇬", code: "+1-268", name: "Antigua and Barbuda"),
            Country(flag: "🇦🇷", code: "+54", name: "Argentina"),
            Country(flag: "🇦🇲", code: "+374", name: "Armenia"),
            Country(flag: "🇦🇼", code: "+297", name: "Aruba"),
            Country(flag: "🇦🇺", code: "+61", name: "Australia"),
            Country(flag: "🇦🇹", code: "+43", name: "Austria"),
            Country(flag: "🇦🇿", code: "+994", name: "Azerbaijan"),
            Country(flag: "🇧🇸", code: "+1-242", name: "Bahamas"),
            Country(flag: "🇧🇭", code: "+973", name: "Bahrain"),
            Country(flag: "🇧🇩", code: "+880", name: "Bangladesh"),
            Country(flag: "🇧🇧", code: "+1-246", name: "Barbados"),
            Country(flag: "🇧🇾", code: "+375", name: "Belarus"),
            Country(flag: "🇧🇪", code: "+32", name: "Belgium"),
            Country(flag: "🇧🇿", code: "+501", name: "Belize"),
            Country(flag: "🇧🇯", code: "+229", name: "Benin"),
            Country(flag: "🇧🇲", code: "+1-441", name: "Bermuda"),
            Country(flag: "🇧🇹", code: "+975", name: "Bhutan"),
            Country(flag: "🇧🇴", code: "+591", name: "Bolivia"),
            Country(flag: "🇧🇶", code: "+599", name: "Bonaire, Sint Eustatius and Saba"),
            Country(flag: "🇧🇦", code: "+387", name: "Bosnia and Herzegovina"),
            Country(flag: "🇧🇼", code: "+267", name: "Botswana"),
            Country(flag: "🇧🇷", code: "+55", name: "Brazil"),
            Country(flag: "🇮🇴", code: "+246", name: "British Indian Ocean Territory"),
            Country(flag: "🇻🇬", code: "+1-284", name: "British Virgin Islands"),
            Country(flag: "🇧🇳", code: "+673", name: "Brunei Darussalam"),
            Country(flag: "🇧🇬", code: "+359", name: "Bulgaria"),
            Country(flag: "🇧🇫", code: "+226", name: "Burkina Faso"),
            Country(flag: "🇧🇮", code: "+257", name: "Burundi"),
            Country(flag: "🇰🇭", code: "+855", name: "Cambodia"),
            Country(flag: "🇨🇲", code: "+237", name: "Cameroon"),
            Country(flag: "🇨🇦", code: "+1", name: "Canada"),
            Country(flag: "🇨🇻", code: "+238", name: "Cape Verde"),
            Country(flag: "🇰🇾", code: "+1-345", name: "Cayman Islands"),
            Country(flag: "🇨🇫", code: "+236", name: "Central African Republic"),
            Country(flag: "🇹🇩", code: "+235", name: "Chad"),
            Country(flag: "🇨🇱", code: "+56", name: "Chile"),
            Country(flag: "🇨🇳", code: "+86", name: "China"),
            Country(flag: "🇨🇽", code: "+61", name: "Christmas Island"),
            Country(flag: "🇨🇨", code: "+61", name: "Cocos (Keeling) Islands"),
            Country(flag: "🇨🇴", code: "+57", name: "Colombia"),
            Country(flag: "🇰🇲", code: "+269", name: "Comoros"),
            Country(flag: "🇨🇬", code: "+242", name: "Congo"),
            Country(flag: "🇨🇩", code: "+243", name: "Congo (Democratic Republic)"),
            Country(flag: "🇨🇰", code: "+682", name: "Cook Islands"),
            Country(flag: "🇨🇷", code: "+506", name: "Costa Rica"),
            Country(flag: "🇭🇷", code: "+385", name: "Croatia"),
            Country(flag: "🇨🇺", code: "+53", name: "Cuba"),
            Country(flag: "🇨🇼", code: "+599", name: "Curaçao"),
            Country(flag: "🇨🇾", code: "+357", name: "Cyprus"),
            Country(flag: "🇨🇿", code: "+420", name: "Czech Republic"),
            Country(flag: "🇩🇰", code: "+45", name: "Denmark"),
            Country(flag: "🇩🇯", code: "+253", name: "Djibouti"),
            Country(flag: "🇩🇲", code: "+1-767", name: "Dominica"),
            Country(flag: "🇩🇴", code: "+1-809", name: "Dominican Republic"),
            Country(flag: "🇪🇨", code: "+593", name: "Ecuador"),
            Country(flag: "🇪🇬", code: "+20", name: "Egypt"),
            Country(flag: "🇸🇻", code: "+503", name: "El Salvador"),
            Country(flag: "🇬🇶", code: "+240", name: "Equatorial Guinea"),
            Country(flag: "🇪🇷", code: "+291", name: "Eritrea"),
            Country(flag: "🇪🇪", code: "+372", name: "Estonia"),
            Country(flag: "🇸🇿", code: "+268", name: "Eswatini"),
            Country(flag: "🇪🇹", code: "+251", name: "Ethiopia"),
            Country(flag: "🇫🇰", code: "+500", name: "Falkland Islands"),
            Country(flag: "🇫🇴", code: "+298", name: "Faroe Islands"),
            Country(flag: "🇫🇯", code: "+679", name: "Fiji"),
            Country(flag: "🇫🇮", code: "+358", name: "Finland"),
            Country(flag: "🇫🇷", code: "+33", name: "France"),
            Country(flag: "🇬🇫", code: "+594", name: "French Guiana"),
            Country(flag: "🇵🇫", code: "+689", name: "French Polynesia"),
            Country(flag: "🇹🇫", code: "+262", name: "French Southern Territories"),
            Country(flag: "🇬🇦", code: "+241", name: "Gabon"),
            Country(flag: "🇬🇲", code: "+220", name: "Gambia"),
            Country(flag: "🇬🇪", code: "+995", name: "Georgia"),
            Country(flag: "🇩🇪", code: "+49", name: "Germany"),
            Country(flag: "🇬🇭", code: "+233", name: "Ghana"),
            Country(flag: "🇬🇮", code: "+350", name: "Gibraltar"),
            Country(flag: "🇬🇷", code: "+30", name: "Greece"),
            Country(flag: "🇬🇱", code: "+299", name: "Greenland"),
            Country(flag: "🇬🇩", code: "+1-473", name: "Grenada"),
            Country(flag: "🇬🇵", code: "+590", name: "Guadeloupe"),
            Country(flag: "🇬🇺", code: "+1-671", name: "Guam"),
            Country(flag: "🇬🇹", code: "+502", name: "Guatemala"),
            Country(flag: "🇬🇬", code: "+44", name: "Guernsey"),
            Country(flag: "🇬🇳", code: "+224", name: "Guinea"),
            Country(flag: "🇬🇼", code: "+245", name: "Guinea-Bissau"),
            Country(flag: "🇬🇾", code: "+592", name: "Guyana"),
            Country(flag: "🇭🇹", code: "+509", name: "Haiti"),
            Country(flag: "🇭🇳", code: "+504", name: "Honduras"),
            Country(flag: "🇭🇰", code: "+852", name: "Hong Kong"),
            Country(flag: "🇭🇺", code: "+36", name: "Hungary"),
            Country(flag: "🇮🇸", code: "+354", name: "Iceland"),
            Country(flag: "🇮🇳", code: "+91", name: "India"),
            Country(flag: "🇮🇩", code: "+62", name: "Indonesia"),
            Country(flag: "🇮🇷", code: "+98", name: "Iran"),
            Country(flag: "🇮🇶", code: "+964", name: "Iraq"),
            Country(flag: "🇮🇪", code: "+353", name: "Ireland"),
            Country(flag: "🇮🇲", code: "+44", name: "Isle of Man"),
            Country(flag: "🇮🇱", code: "+972", name: "Israel"),
            Country(flag: "🇮🇹", code: "+39", name: "Italy"),
            Country(flag: "🇯🇲", code: "+1-876", name: "Jamaica"),
            Country(flag: "🇯🇵", code: "+81", name: "Japan"),
            Country(flag: "🇯🇪", code: "+44", name: "Jersey"),
            Country(flag: "🇯🇴", code: "+962", name: "Jordan"),
            Country(flag: "🇰🇿", code: "+7", name: "Kazakhstan"),
            Country(flag: "🇰🇪", code: "+254", name: "Kenya"),
            Country(flag: "🇰🇮", code: "+686", name: "Kiribati"),
            Country(flag: "🇽🇰", code: "+383", name: "Kosovo"),
            Country(flag: "🇰🇼", code: "+965", name: "Kuwait"),
            Country(flag: "🇰🇬", code: "+996", name: "Kyrgyzstan"),
            Country(flag: "🇱🇦", code: "+856", name: "Laos"),
            Country(flag: "🇱🇻", code: "+371", name: "Latvia"),
            Country(flag: "🇱🇧", code: "+961", name: "Lebanon"),
            Country(flag: "🇱🇸", code: "+266", name: "Lesotho"),
            Country(flag: "🇱🇷", code: "+231", name: "Liberia"),
            Country(flag: "🇱🇾", code: "+218", name: "Libya"),
            Country(flag: "🇱🇮", code: "+423", name: "Liechtenstein"),
            Country(flag: "🇱🇹", code: "+370", name: "Lithuania"),
            Country(flag: "🇱🇺", code: "+352", name: "Luxembourg"),
            Country(flag: "🇲🇴", code: "+853", name: "Macao"),
            Country(flag: "🇲🇬", code: "+261", name: "Madagascar"),
            Country(flag: "🇲🇼", code: "+265", name: "Malawi"),
            Country(flag: "🇲🇾", code: "+60", name: "Malaysia"),
            Country(flag: "🇲🇻", code: "+960", name: "Maldives"),
            Country(flag: "🇲🇱", code: "+223", name: "Mali"),
            Country(flag: "🇲🇹", code: "+356", name: "Malta"),
            Country(flag: "🇲🇭", code: "+692", name: "Marshall Islands"),
            Country(flag: "🇲🇶", code: "+596", name: "Martinique"),
            Country(flag: "🇲🇷", code: "+222", name: "Mauritania"),
            Country(flag: "🇲🇺", code: "+230", name: "Mauritius"),
            Country(flag: "🇾🇹", code: "+262", name: "Mayotte"),
            Country(flag: "🇲🇽", code: "+52", name: "Mexico"),
            Country(flag: "🇫🇲", code: "+691", name: "Micronesia"),
            Country(flag: "🇲🇩", code: "+373", name: "Moldova"),
            Country(flag: "🇲🇨", code: "+377", name: "Monaco"),
            Country(flag: "🇲🇳", code: "+976", name: "Mongolia"),
            Country(flag: "🇲🇪", code: "+382", name: "Montenegro"),
            Country(flag: "🇲🇸", code: "+1-664", name: "Montserrat"),
            Country(flag: "🇲🇦", code: "+212", name: "Morocco"),
            Country(flag: "🇲🇿", code: "+258", name: "Mozambique"),
            Country(flag: "🇲🇲", code: "+95", name: "Myanmar"),
            Country(flag: "🇳🇦", code: "+264", name: "Namibia"),
            Country(flag: "🇳🇷", code: "+674", name: "Nauru"),
            Country(flag: "🇳🇵", code: "+977", name: "Nepal"),
            Country(flag: "🇳🇱", code: "+31", name: "Netherlands"),
            Country(flag: "🇳🇨", code: "+687", name: "New Caledonia"),
            Country(flag: "🇳🇿", code: "+64", name: "New Zealand"),
            Country(flag: "🇳🇮", code: "+505", name: "Nicaragua"),
            Country(flag: "🇳🇪", code: "+227", name: "Niger"),
            Country(flag: "🇳🇬", code: "+234", name: "Nigeria"),
            Country(flag: "🇳🇺", code: "+683", name: "Niue"),
            Country(flag: "🇳🇫", code: "+672", name: "Norfolk Island"),
            Country(flag: "🇰🇵", code: "+850", name: "North Korea"),
            Country(flag: "🇲🇰", code: "+389", name: "North Macedonia"),
            Country(flag: "🇲🇵", code: "+1-670", name: "Northern Mariana Islands"),
            Country(flag: "🇳🇴", code: "+47", name: "Norway"),
            Country(flag: "🇴🇲", code: "+968", name: "Oman"),
            Country(flag: "🇵🇰", code: "+92", name: "Pakistan"),
            Country(flag: "🇵🇼", code: "+680", name: "Palau"),
            Country(flag: "🇵🇸", code: "+970", name: "Palestine"),
            Country(flag: "🇵🇦", code: "+507", name: "Panama"),
            Country(flag: "🇵🇬", code: "+675", name: "Papua New Guinea"),
            Country(flag: "🇵🇾", code: "+595", name: "Paraguay"),
            Country(flag: "🇵🇪", code: "+51", name: "Peru"),
            Country(flag: "🇵🇭", code: "+63", name: "Philippines"),
            Country(flag: "🇵🇳", code: "+64", name: "Pitcairn"),
            Country(flag: "🇵🇱", code: "+48", name: "Poland"),
            Country(flag: "🇵🇹", code: "+351", name: "Portugal"),
            Country(flag: "🇵🇷", code: "+1-787", name: "Puerto Rico"),
            Country(flag: "🇶🇦", code: "+974", name: "Qatar"),
            Country(flag: "🇷🇪", code: "+262", name: "Réunion"),
            Country(flag: "🇷🇴", code: "+40", name: "Romania"),
            Country(flag: "🇷🇺", code: "+7", name: "Russia"),
            Country(flag: "🇷🇼", code: "+250", name: "Rwanda"),
            Country(flag: "🇧🇱", code: "+590", name: "Saint Barthélemy"),
            Country(flag: "🇸🇭", code: "+290", name: "Saint Helena"),
            Country(flag: "🇰🇳", code: "+1-869", name: "Saint Kitts and Nevis"),
            Country(flag: "🇱🇨", code: "+1-758", name: "Saint Lucia"),
            Country(flag: "🇲🇫", code: "+590", name: "Saint Martin"),
            Country(flag: "🇵🇲", code: "+508", name: "Saint Pierre and Miquelon"),
            Country(flag: "🇻🇨", code: "+1-784", name: "Saint Vincent and the Grenadines"),
            Country(flag: "🇼🇸", code: "+685", name: "Samoa"),
            Country(flag: "🇸🇲", code: "+378", name: "San Marino"),
            Country(flag: "🇸🇹", code: "+239", name: "São Tomé and Príncipe"),
            Country(flag: "🇸🇦", code: "+966", name: "Saudi Arabia"),
            Country(flag: "🇸🇳", code: "+221", name: "Senegal"),
            Country(flag: "🇷🇸", code: "+381", name: "Serbia"),
            Country(flag: "🇸🇨", code: "+248", name: "Seychelles"),
            Country(flag: "🇸🇱", code: "+232", name: "Sierra Leone"),
            Country(flag: "🇸🇬", code: "+65", name: "Singapore"),
            Country(flag: "🇸🇽", code: "+1-721", name: "Sint Maarten"),
            Country(flag: "🇸🇰", code: "+421", name: "Slovakia"),
            Country(flag: "🇸🇮", code: "+386", name: "Slovenia"),
            Country(flag: "🇸🇧", code: "+677", name: "Solomon Islands"),
            Country(flag: "🇸🇴", code: "+252", name: "Somalia"),
            Country(flag: "🇿🇦", code: "+27", name: "South Africa"),
            Country(flag: "🇬🇸", code: "+500", name: "South Georgia and the South Sandwich Islands"),
            Country(flag: "🇰🇷", code: "+82", name: "South Korea"),
            Country(flag: "🇸🇸", code: "+211", name: "South Sudan"),
            Country(flag: "🇪🇸", code: "+34", name: "Spain"),
            Country(flag: "🇱🇰", code: "+94", name: "Sri Lanka"),
            Country(flag: "🇸🇩", code: "+249", name: "Sudan"),
            Country(flag: "🇸🇷", code: "+597", name: "Suriname"),
            Country(flag: "🇸🇯", code: "+47", name: "Svalbard and Jan Mayen"),
            Country(flag: "🇸🇿", code: "+268", name: "Swaziland"),
            Country(flag: "🇸🇪", code: "+46", name: "Sweden"),
            Country(flag: "🇨🇭", code: "+41", name: "Switzerland"),
            Country(flag: "🇸🇾", code: "+963", name: "Syria"),
            Country(flag: "🇹🇼", code: "+886", name: "Taiwan"),
            Country(flag: "🇹🇯", code: "+992", name: "Tajikistan"),
            Country(flag: "🇹🇿", code: "+255", name: "Tanzania"),
            Country(flag: "🇹🇭", code: "+66", name: "Thailand"),
            Country(flag: "🇹🇱", code: "+670", name: "Timor-Leste"),
            Country(flag: "🇹🇬", code: "+228", name: "Togo"),
            Country(flag: "🇹🇰", code: "+690", name: "Tokelau"),
            Country(flag: "🇹🇴", code: "+676", name: "Tonga"),
            Country(flag: "🇹🇹", code: "+1-868", name: "Trinidad and Tobago"),
            Country(flag: "🇹🇳", code: "+216", name: "Tunisia"),
            Country(flag: "🇹🇷", code: "+90", name: "Turkey"),
            Country(flag: "🇹🇲", code: "+993", name: "Turkmenistan"),
            Country(flag: "🇹🇨", code: "+1-649", name: "Turks and Caicos Islands"),
            Country(flag: "🇹🇻", code: "+688", name: "Tuvalu"),
            Country(flag: "🇺🇬", code: "+256", name: "Uganda"),
            Country(flag: "🇺🇦", code: "+380", name: "Ukraine"),
            Country(flag: "🇦🇪", code: "+971", name: "United Arab Emirates"),
            Country(flag: "🇬🇧", code: "+44", name: "United Kingdom"),
            Country(flag: "🇺🇸", code: "+1", name: "United States"),
            Country(flag: "🇺🇾", code: "+598", name: "Uruguay"),
            Country(flag: "🇺🇿", code: "+998", name: "Uzbekistan"),
            Country(flag: "🇻🇺", code: "+678", name: "Vanuatu"),
            Country(flag: "🇻🇪", code: "+58", name: "Venezuela"),
            Country(flag: "🇻🇳", code: "+84", name: "Vietnam"),
            Country(flag: "🇼🇫", code: "+681", name: "Wallis and Futuna"),
            Country(flag: "🇪🇭", code: "+212", name: "Western Sahara"),
            Country(flag: "🇾🇪", code: "+967", name: "Yemen"),
            Country(flag: "🇿🇲", code: "+260", name: "Zambia"),
            Country(flag: "🇿🇼", code: "+263", name: "Zimbabwe"),
        ]
        
    func sortedCountryCodes() -> [Country] {
        let preferredCountries = ["Russia", "Ukraine", "Belarus", "Kazakhstan", "Armenia", "Turkey", "Georgia", "Serbia", "Cyprus"]
        let preferred = countryCodes.filter { preferredCountries.contains($0.name) }
        let others = countryCodes.filter { !preferredCountries.contains($0.name) }
        return preferred + others
    }
}

